apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nkp0w9e6w-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nkp0w9e6w-go 
  name: nkp0w9e6w-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nkp0w9e6w-go 
